### PR TITLE
display CSalienInfoBox during battle screen

### PR DESCRIPTION
**Pull request by Gummibeer**
**adds:** #19

### CODE REVIEW

**Comment by Gummibeer** [comment]
It adds the info screen everytime the function runs - have to do it just once per round.

**Comment by Wiethoofd** [comment]
Move it inside the `setTimeout` in the `joinZone` function where it sets the *gameCheck intervalFunc*, then it loads the planet and base and only inserts the info box once.

**Comment by Farogan** [comment]
Yes as @Wiethoofd says. I tested it and it started to take lots of performance.

**Comment by coryshaw1** [comment]
Closed by 16703828c1069b8a3d8176f63a2e5475a1696314

This only tries to add the profile box once at the begging of a round, and if one already exists, the existing box is destroyed to make room for the new box. Keeping memory down.

**Pull request closed without merging**
