### PR TITLE
force score to be an integer

### PR DESCRIPTION
**Pull request by Gummibeer**
**fixes** #22

### CODE REVIEW

**Comment by coryshaw1** [comment]
Should we do `Math.round` just in case? I haven't seen 599.9999, but just to be on the safe side.

**Comment by Gummibeer** [comment]
I don't know if it will fail if it's too low (has an impossible value)? If it's too high it will definitely.
Wouldn't it be easier to do not touch the score logic? It will get to the max score in every case - because the game runs successful the maximum round-time.

**Comment by coryshaw1** [comment]
I think the code is needed if the tab isn't active, the score doesn't increase as fast. Probably from other enemies not spawning. Need more info, and am open to suggestions.

`Math.round` would have the same effect as using `Math.floor` in the impossible value sense.

**Comment by Gummibeer** [comment]
It's changed 😃

**Pull request merged**
